package com.btg.accrualfeesv2.enums

enum class PermissaoEnum {
    APROVAR,
    REPROVAR_TODAS,
    REPROVAR_SOMENTE_PROPRIA_REVERSAO_CRIADA,
    VISUALIZAR_TODAS,
    VISUALIZAR_SOMENTE_PROPRIA_REVERSAO_CRIADA
}
